{{- if .Values.certificate.enabled -}} 
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
spec:
  secretName: {{ .Values.certificate.secretName }}
  issuerRef:
    name: {{ .Values.certificate.issuerRef.name }}
    kind: {{ .Values.certificate.issuerRef.kind }}
  #commonName: "*.{{ .Values.certificate.domain }}"
  dnsNames:
    - "{{ .Values.certificate.domain }}"
    - "*.{{ .Values.certificate.domain }}"
{{- end -}}