name: "Login to Docker"
description: "Login to Docker, both Docker Hub and AWS ECR"
inputs:
   docker-hub-username:
     description: "docker-hub-username"
   docker-hub-password:
     description: "docker-hub-password"
   aws-assume-role:
     description: "Role for to assume for AWS"
outputs:
  ecr-registry:
    description: "ecr-registry"
    value: ${{ steps.login-ecr.outputs.registry }}
runs:
  using: "composite"
  steps:
  - name: Login to Docker Hub
    if: inputs.docker-hub-username && inputs.docker-hub-password
    uses: docker/login-action@v2
    with:
      username: ${{ inputs.docker-hub-username }}
      password: ${{ inputs.docker-hub-password }}

  - name: Configure AWS credentials
    if: inputs.aws-assume-role
    uses: aws-actions/configure-aws-credentials@v1
    with:
      role-to-assume:  ${{ inputs.aws-assume-role }}
      aws-region: us-east-1

  - name: Login to Amazon ECR
    id: login-ecr
    uses: aws-actions/amazon-ecr-login@v1

