name: "GitOps"
description: "Run GitOps"
inputs:
  values-script:
    description: "Script to run to update values.yaml file"
  preview-values:
    description: "values to create values.preview.yaml file"
  preview-values-script:
    description: "Script to run to update values.preview.yaml file"
  repository:
    required: true
    description: "Repo to use for GitOps"
  repository-ssh-key:
    required: true
    description: "SSH Key to use to authenticate GitOps repo"
  input-directory:
    required: true
    description: "Input directory, usually containing a helm chart to sync over to GitOps repo"
  output-directory:
    required: true
    description: "Output directory, in the GitOps repo to place the output, usually a helm chart"
  message:
    required: true
    description: "Message to use as part of the GitOps commit"
  user-name:
    required: true
    default: O2V2
    description: "Message to use as part of the GitOps commit"
  user-email:
    required: true
    default: ci@ovatu.com
    description: "Message to use as part of the GitOps commit"
runs:
  using: "composite"
  steps:
    - name: Checkout GitOps repo
      uses: actions/checkout@v3
      with: 
        repository: ${{ inputs.repository }}
        ssh-key: ${{ inputs.repository-ssh-key }}
        path: ./gitops

    - name: "Sync input directory to output directory"
      shell: bash
      run: rsync -vr --delete $GITHUB_WORKSPACE/${{ inputs.input-directory }} $GITHUB_WORKSPACE/gitops/${{ inputs.output-directory }}

    - name: Merge values
      if: inputs.values
      shell: bash
      working-directory: gitops/${{ inputs.output-directory }}
      run: echo "${{ inputs.values }}" | yq m values.yaml -

    - name: Create preview values
      if: inputs.preview-values
      shell: bash
      working-directory: gitops/${{ inputs.output-directory }}
      run: |
        touch values.preview.yaml
        echo "${{ inputs.preview-values }}" >> values.preview.yaml

    - name: Run preview-values script
      if: inputs.values-script
      shell: bash
      working-directory: gitops/${{ inputs.output-directory }}
      run: |
        touch values.preview.yaml
        ${{ inputs.values-script }}

    - name: "Commit changes to GitOps repo"
      shell: bash
      working-directory: gitops/${{ inputs.output-directory }}
      run: |
        git config user.name ${{ inputs.user-name }}
        git config user.email ${{ inputs.user-email }}

        git add .

        if [ -n "$(git status --porcelain)" ]; then
          git commit -am "${{ inputs.message }}"
          git push
        fi
