name: Docker Build -> Docker Hub + AWS ECR

on:
  workflow_call:
    inputs:
      docker-repo:
        description: Name of the docker repo
        type: string
        required: true
      docker-tag:
        description: Name of the docker tag
        type: string
        required: true
      docker-file:
        description: Location of Dockerfile
        type: string
      docker-platforms:
        description: Docker build platforms
        type: string
        default: linux/amd64
    secrets:
      AWS_ASSUME_ROLE:
        required: true
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_PASSWORD:
        required: true
      SLACK_WEBHOOK_URL:
        required: true

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker
      id: docker-login
      uses: ovatu/actions/.github/actions/docker-login@main
      with:
        docker-hub-username: ${{ secrets.DOCKER_HUB_USERNAME }}
        docker-hub-password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        aws-assume-role: ${{ secrets.AWS_ASSUME_ROLE }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        file: deploy/kubernetes/docker/Dockerfile
        platforms: ${{ inputs.docker-platforms }}
        push: true
        tags: |
          ${{ inputs.docker-repo }}:${{ inputs.docker-tag }}
          ${{ steps.docker-login.outputs.ecr-registry }}/${{ inputs.docker-repo }}:${{ inputs.docker-tag }}
        build-args: |
          VERSION=${{ inputs.docker-tag }}