name: Docker Build -> Docker Hub + AWS ECR -> Gitops

on:
  workflow_call:
    inputs:
      name:
        description: Repo for gitops
        type: string
        required: true
      gitops-repo:
        description: Repo for gitops
        type: string
        required: true
      gitops-name:
        description: Name of the gitops app
        type: string
        required: true
    secrets:
      GITOPS_REPO_PRIVATE_KEY:
        required: true
      SLACK_WEBHOOK_URL:
        required: true

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set variables
      id: variables
      run: |
        SLUG=$(echo "${{ github.event.ref }}" | iconv -t ascii//TRANSLIT | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z)

        echo "branch=${{ github.event.ref }}" >> $GITHUB_OUTPUT
        echo "slug=$SLUG" >> $GITHUB_OUTPUT

    - name: Gitops cleanup
      uses: ovatu/actions/.github/actions/gitops-cleanup@main
      with:
        repository: ${{ inputs.gitops-repo }}
        repository-ssh-key: ${{ secrets.GITOPS_REPO_PRIVATE_KEY }}
        directory: charts/${{ inputs.gitops-name }}/branches/${{ steps.variables.outputs.slug }}
        message: "[Actions][Cleanup] repo:${{ inputs.gitops-name }}, branch: ${{ steps.variables.outputs.branch }}"

    - name: Send Slack webhook
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "text": "Preview deleted: ${{ inputs.name }} / ${{ steps.variables.outputs.branch }}",
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "Preview deleted: ${{ inputs.name }} / ${{ steps.variables.outputs.branch }}"
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "*App:* ${{ inputs.gitops-name }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Repo:* ${{ github.repository }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Branch:* ${{ steps.variables.outputs.branch }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
