name: Docker Build -> Docker Hub + AWS ECR -> Gitops (canary)

on:
  workflow_call:
    inputs:
      name:
        description: Friendly name of the app
        type: string
        required: true
      docker-name:
        description: Name of the docker image
        type: string
        required: true
      docker-file:
        description: Location of Dockerfile
        type: string
      docker-platforms:
        description: Docker build platforms
        type: string
        default: linux/amd64
      helm-chart:
        description: Location of helm charts
        type: string
      gitops-repo:
        description: Repo for gitops
        type: string
        required: true
      gitops-name:
        description: Name of the gitops app
        type: string
        required: true
      gitops-canary:
        description: Create canary
        type: boolean
        default: false
      gitops-values-script:
        description: Script to run during gitops (update values.yaml)
        type: string
      gitops-canary-values-script:
        description: Script to run during gitops (update canary values.yaml)
        type: string
      gitops-canary-master-values-path:
        description: master values from bootstrap to copy
        type: string
      gitops-ingress-path:
        description: path to ingress
        type: string
    secrets:
      AWS_ASSUME_ROLE:
        required: true
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_PASSWORD:
        required: true
      GITOPS_REPO_PRIVATE_KEY:
        required: true
      GITHUB_REPOS_PAT:
        required: false
      SLACK_WEBHOOK_URL:
        required: true

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set variables
      id: variables
      run: |
        SLUG=$(echo "${{ github.ref_name }}" | iconv -t ascii//TRANSLIT | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z)
        REF=$(git rev-parse --short "$GITHUB_SHA")
        echo "repo=${{ inputs.docker-name }}" >> $GITHUB_OUTPUT
        echo "tag=$SLUG-$REF" >> $GITHUB_OUTPUT
        echo "canary=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        echo "slug=$SLUG" >> $GITHUB_OUTPUT

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker
      id: docker-login
      uses: ovatu/actions/.github/actions/docker-login@main
      with:
        docker-hub-username: ${{ secrets.DOCKER_HUB_USERNAME }}
        docker-hub-password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        aws-assume-role: ${{ secrets.AWS_ASSUME_ROLE }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        driver: docker
        file: deploy/kubernetes/docker/Dockerfile
        platforms: ${{ inputs.docker-platforms }}
        push: true
        tags: |
          ${{ steps.variables.outputs.repo }}:${{ steps.variables.outputs.tag }}
          ${{ steps.docker-login.outputs.ecr-registry }}/${{ steps.variables.outputs.repo }}:${{ steps.variables.outputs.tag }}
        build-args: |
          VERSION=${{ steps.variables.outputs.tag }}
        secrets: |
          "github_token=${{ secrets.GITHUB_REPOS_PAT }}"

    - name: Gitops
      uses: ovatu/actions/.github/actions/gitops-release@main
      with:
        name: ${{ inputs.gitops-name }}-${{ steps.variables.outputs.slug }}
        repository: ${{ inputs.gitops-repo }}
        repository-ssh-key: ${{ secrets.GITOPS_REPO_PRIVATE_KEY }}
        input-directory: ${{ inputs.helm-chart }}
        output-directory: apps/${{ inputs.gitops-name }}/canaries/${{ steps.variables.outputs.slug }}
        gitops-name: ${{ inputs.gitops-name }}
        canary: ${{ inputs.gitops-canary == true }}
        canary-master-values-path: ${{ inputs.gitops-canary-master-values-path }}
        message: "[Actions][Build] repo:${{ inputs.gitops-name }}, canary: ${{ steps.variables.outputs.canary }}"
        values-script: |
          echo "BEGIN writing values"
          yq -i '.appVersion = "${{ steps.variables.outputs.tag }}"' Chart.yaml
          yq -i '.image.repository = "${{ steps.docker-login.outputs.ecr-registry }}/${{ steps.variables.outputs.repo }}"' values.yaml
          yq -i '.image.tag = "${{ steps.variables.outputs.tag }}"' values.yaml
          echo "DONE writing values"

          echo "BEGIN inputs.gitops-values-script"
          ${{ inputs.gitops-values-script }}
          echo "END inputs.gitops-values-script"
        canary-values-script: |
          echo "BEGIN canary script"
          touch Chart.yaml
          mkdir -p templates
          export CHART_NAME=$(yq '.name' ../chart/Chart.yaml)
          export CHART_VERSION=$(yq '.version' ../chart/Chart.yaml)
          
          yq -i ".name = \"${{ inputs.gitops-name }}-${{ steps.variables.outputs.slug }}\"" Chart.yaml
          yq -i ".version = strenv(CHART_VERSION)" Chart.yaml
          yq -i ".dependencies[0].name = strenv(CHART_NAME)" Chart.yaml
          yq -i ".dependencies[0].version = strenv(CHART_VERSION)" Chart.yaml
          yq -i ".dependencies[0].repository = \"file://../chart\"" Chart.yaml
          yq -i ".dependencies[0].alias = \"canary\"" Chart.yaml

          rsync -vr --delete --exclude '01-certificate.yaml' $GITHUB_ACTION_PATH/templates/ templates/
          
          yq -i ".namespace.enabled = true" values.yaml
          yq -i ".namespace.name = \"${{ inputs.gitops-name }}-${{ steps.variables.outputs.slug }}\"" values.yaml

          yq -i ".canary.enabled = true" values.yaml
          yq -i ".canary.${{ inputs.gitops-ingress-path }}.annotations.\"nginx.ingress.kubernetes.io/canary\" = \"true\"" values.yaml
          yq -i ".canary.${{ inputs.gitops-ingress-path }}.annotations.\"nginx.ingress.kubernetes.io/canary-by-header\" = \"x-canary\"" values.yaml
          yq -i ".canary.${{ inputs.gitops-ingress-path }}.annotations.\"nginx.ingress.kubernetes.io/canary-by-header-value\" = \"true\"" values.yaml
          yq -i ".canary.${{ inputs.gitops-ingress-path }}.annotations.\"nginx.ingress.kubernetes.io/canary-weight\" = \"${{ github.event.inputs.weight }}\"" values.yaml
          yq -i ".canary.${{ inputs.gitops-ingress-path }}.enabled = true" values.yaml
          yq -i ".canary.${{ inputs.gitops-ingress-path }}.gloo = false" values.yaml

          echo "BEGIN inputs.gitops-canary-values-script"
          ${{ inputs.gitops-canary-values-script }}
          echo "END inputs.gitops-canary-values-script"

    - name: Send Slack webhook
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "text": "Canary release deployed: ${{ inputs.name }}, v: ${{ steps.variables.outputs.canary }}, weight: ${{ github.event.inputs.weight }}",
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "Canary release deployed: ${{ inputs.name }}, v: ${{ steps.variables.outputs.canary }}"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ${{ toJson(github.event.release.body || 'No release notes') }}
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "*App:* ${{ inputs.gitops-name }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Version:* ${{ steps.variables.outputs.tag }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Repo:* ${{ github.repository }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Tag:* ${{ github.ref_name }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
